### ISSUE TITLE
Golden / Admin chat isn't replicated on both clients.

### ISSUE THREAD

**Issue by CitizenFoffie** [p0s0/ob-framework#14] opened 2022-01-30 07:16 UTC
**Describe the bug**
When you make a admin have the yellow chat other players don't see the yellow chat

**Comment by CitizenFoffie** [comment] 2022-01-30 07:45
possible fix added to my branch by turning "~= nil" to "== true"
why this works no idea, but it does

**Comment by Cristiano100** [comment] 2022-02-27 04:18
Unable to reproduce

**Comment by p0s0** [comment] 2022-02-28 02:33
Unable to reproduce this issue. Closing

**Closed by p0s0** 2022-02-28 02:33 UTC
Labels: bug
